In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 24.2 Handling Imbalanced Dataset

- Wrt any problem statement that you are working in ML and DL, initially you will be given a data set. 
- So lets consider a dataset, and you are given a classification problem. Here, classification --> Supervised ML. 
- This means the output is basically in the form of categories.(If you have 2 categories than we can say it as a binary classification.)
- So lets condiser a Binary classification, lets say i have 1000 datapoints in my dataset.
- Out of these 1000 datapoints, 900 are 'Yes' datapoints and 100 are 'No' datapoints, so if we see the ratio of Yes:No its 9:1. This tells us that the dataset is imbalanced. 
- The main porblem with the imbalanced data set while you are solving a machine learning application, your model that you are probably creating, which will be responsible in predicting will get biased towards this maximum number of datapoints(900 yes).
- So its necessary that we fix this imbalanced data set, and we try to make sure that both the data points become equal.

## To Handle this, we use two techniques:

## 1. Up Sampling 
## 2. Down Sampling

In [2]:
# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes

n_sample = 1000
class_0_ratio = 0.9
n_class_0 = int(n_sample * class_0_ratio)
n_class_1 = n_sample - n_class_0

In [3]:
n_class_0, n_class_1

(900, 100)

In [5]:
# Creating dataframe with Imbalanced datapoints

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale =1, size = n_class_0),
    'feature_2': np.random.normal(loc=0, scale =1, size = n_class_0),
    'target': [0] * n_class_0
})
class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale =1, size = n_class_1),
    'feature_2': np.random.normal(loc=2, scale =1, size = n_class_1),
    'target': [1] * n_class_1
})

In [7]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [8]:
df

     feature_1  feature_2  target
0    -1.085631   0.551302       0
1     0.997345   0.419589       0
2     0.282978   1.815652       0
3    -1.506295  -0.252750       0
4    -0.578600  -0.292004       0
..         ...        ...     ...
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

[1000 rows x 3 columns]

In [10]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

## --> Up Sampling

In [ ]:
# for rows with value as 1:
df_minority = df[df['target']==1]
# for rows with value as 0:
df_majority = df[df['target']==0]

In [12]:
from sklearn.utils import resample
# This basically extrapolates the point: it means that whatever is the minority it will try to create new points for it, and it will try to equalize with respect to the majority.

In [ ]:
'''
Synatx: 
resample(minority parameter, replace = True, n_samples = len(majority), random_state = anyvalue)
arg 1: For which sample we want to probably performing upsampling.

arg 2: Here replace basically means that whenever I am performing the resampling over here, this sample will get added with the replacement.(So different different data points can be added over here.)

arg 3: How many we have to increase, here i will give the length of the majority population.

arg 4: for any random state value
'''

In [ ]:
df_minority_upsampling = resample(df_minority, 
                                  replace = True, 
                                  n_samples = len(df_majority), 
                                  random_state = 42)

In [15]:
df_minority_upsampling.shape

(900, 3)

In [16]:
df_minority_upsampling.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [18]:
df_upsampled = pd.concat([df_majority, df_minority_upsampling])
df_upsampled

     feature_1  feature_2  target
0    -1.085631   0.551302       0
1     0.997345   0.419589       0
2     0.282978   1.815652       0
3    -1.506295  -0.252750       0
4    -0.578600  -0.292004       0
..         ...        ...     ...
952   1.188902   2.189189       1
965   3.919526   1.980541       1
976   2.810326   3.604614       1
942   3.621531   2.168229       1
974   1.160887   2.489203       1

[1800 rows x 3 columns]

In [21]:

df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## --> Down Sampling

In [22]:
# Creating dataframe with Imbalanced datapoints

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale =1, size = n_class_0),
    'feature_2': np.random.normal(loc=0, scale =1, size = n_class_0),
    'target': [0] * n_class_0
})
class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale =1, size = n_class_1),
    'feature_2': np.random.normal(loc=2, scale =1, size = n_class_1),
    'target': [1] * n_class_1
})

In [23]:
dfd = pd.concat([class_0, class_1]).reset_index(drop=True)

In [24]:
dfd['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [25]:
# for rows with value as 1:
dfd_minority = dfd[dfd['target']==1]
# for rows with value as 0:
dfd_majority = dfd[dfd['target']==0]

In [26]:
dfd_majority_downsampling = resample(dfd_majority, 
                                  replace = False, 
                                  n_samples = len(dfd_minority), 
                                  random_state = 42)

''' 
Here in arg 2: we dont want ro replce data...we are reducing the data points
'''

' \nHere in arg 2: we dont want ro replce data...we are reducing the data points\n'

In [27]:
dfd_majority_downsampling.shape

(100, 3)

In [28]:
dfd_downsampled = pd.concat([dfd_minority, dfd_majority_downsampling])
dfd_downsampled

     feature_1  feature_2  target
900  -0.643425   2.571923       1
901   1.551009   1.782767       1
902   1.641093   2.054318       1
903   2.133194   2.155998       1
904   1.355758   2.467810       1
..         ...        ...     ...
398   1.013666   0.083496       0
76    0.164480  -1.808980       0
196  -1.576624   0.525893       0
631  -0.540147   0.610282       0
751  -0.168798  -0.831334       0

[200 rows x 3 columns]

In [29]:
dfd_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64